# https://qiita.com/kerupani129/items/fda97ed2cf34a156d47d
name: Prevent scheduled workflow from being automatically disabled

on:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

jobs:

  keepalive:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: keep-active

      - name: Commit and push
        env:
          NAME: 'github-actions[bot]'
          EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
        run: |
          git -c user.name="$NAME" -c user.email="$EMAIL" commit --allow-empty -m 'Automated commit'
          git push
